version: "3.9"
services:
  config-server:
    build: ./config-server/
    restart: unless-stopped
    ports:
      - "8071:8071"
    healthcheck:
        test: "wget --no-verbose --tries=1 --spider config-server:8071/api/actuator/health || exit 1"
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 2s

  eureka-server:
    build: ./eureka-server/
    restart: unless-stopped
    ports:
      - "8761:8761"
    depends_on:
      config-server:
        condition: service_healthy

  gateway-server:
    build: ./gateway-server/
    restart: unless-stopped
    ports:
      - "8072:8072"
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_started

  address-service:
    build: ./address-service/
    restart: unless-stopped
    ports:
      - "8082:8082"
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_started

  manager-service:
    build: ./manager-service/
    restart: unless-stopped
    ports:
      - "8081:8081"
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_started
      address-service:
        condition: service_started